// Code generated by protoc-gen-go. DO NOT EDIT.
// source: KbInfo.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KbInfoRequest struct {
	// @inject_tag: json:"kb_id"
	Id                   []int64  `protobuf:"varint,1,rep,packed,name=id,proto3" json:"kb_id"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KbInfoRequest) Reset()         { *m = KbInfoRequest{} }
func (m *KbInfoRequest) String() string { return proto.CompactTextString(m) }
func (*KbInfoRequest) ProtoMessage()    {}
func (*KbInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99d1ca54f6ea3338, []int{0}
}

func (m *KbInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KbInfoRequest.Unmarshal(m, b)
}
func (m *KbInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KbInfoRequest.Marshal(b, m, deterministic)
}
func (m *KbInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KbInfoRequest.Merge(m, src)
}
func (m *KbInfoRequest) XXX_Size() int {
	return xxx_messageInfo_KbInfoRequest.Size(m)
}
func (m *KbInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KbInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KbInfoRequest proto.InternalMessageInfo

func (m *KbInfoRequest) GetId() []int64 {
	if m != nil {
		return m.Id
	}
	return nil
}

type KbInfoResponse struct {
	// @inject_tag: json:"result"
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KbInfoResponse) Reset()         { *m = KbInfoResponse{} }
func (m *KbInfoResponse) String() string { return proto.CompactTextString(m) }
func (*KbInfoResponse) ProtoMessage()    {}
func (*KbInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_99d1ca54f6ea3338, []int{1}
}

func (m *KbInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KbInfoResponse.Unmarshal(m, b)
}
func (m *KbInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KbInfoResponse.Marshal(b, m, deterministic)
}
func (m *KbInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KbInfoResponse.Merge(m, src)
}
func (m *KbInfoResponse) XXX_Size() int {
	return xxx_messageInfo_KbInfoResponse.Size(m)
}
func (m *KbInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KbInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KbInfoResponse proto.InternalMessageInfo

func (m *KbInfoResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func init() {
	proto.RegisterType((*KbInfoRequest)(nil), "services.KbInfoRequest")
	proto.RegisterType((*KbInfoResponse)(nil), "services.KbInfoResponse")
}

func init() { proto.RegisterFile("KbInfo.proto", fileDescriptor_99d1ca54f6ea3338) }

var fileDescriptor_99d1ca54f6ea3338 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf1, 0x4e, 0xf2, 0xcc,
	0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c,
	0x4e, 0x2d, 0x56, 0x92, 0xe7, 0xe2, 0x85, 0xc8, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08,
	0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6b, 0x30, 0x07, 0x31, 0x65, 0xa6, 0x28,
	0x69, 0x70, 0xf1, 0xc1, 0x14, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x71, 0xb1, 0x15,
	0xa5, 0x16, 0x97, 0xe6, 0x94, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x04, 0x41, 0x79, 0x46, 0x51,
	0x30, 0xa3, 0x82, 0x21, 0x86, 0x0b, 0x79, 0x72, 0x09, 0x85, 0x16, 0xa4, 0x24, 0x96, 0xa4, 0x7a,
	0x27, 0xb9, 0xa4, 0x96, 0x24, 0x66, 0xe6, 0xf8, 0x64, 0x16, 0x97, 0x08, 0x89, 0xeb, 0xc1, 0x2c,
	0xd7, 0x43, 0xb1, 0x59, 0x4a, 0x02, 0x53, 0x02, 0x62, 0xa3, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0xdd,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x4b, 0x49, 0x99, 0xc7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KbInfoServiceClient is the client API for KbInfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KbInfoServiceClient interface {
	UpdateKbDetailList(ctx context.Context, in *KbInfoRequest, opts ...grpc.CallOption) (*KbInfoResponse, error)
}

type kbInfoServiceClient struct {
	cc *grpc.ClientConn
}

func NewKbInfoServiceClient(cc *grpc.ClientConn) KbInfoServiceClient {
	return &kbInfoServiceClient{cc}
}

func (c *kbInfoServiceClient) UpdateKbDetailList(ctx context.Context, in *KbInfoRequest, opts ...grpc.CallOption) (*KbInfoResponse, error) {
	out := new(KbInfoResponse)
	err := c.cc.Invoke(ctx, "/services.KbInfoService/UpdateKbDetailList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KbInfoServiceServer is the server API for KbInfoService service.
type KbInfoServiceServer interface {
	UpdateKbDetailList(context.Context, *KbInfoRequest) (*KbInfoResponse, error)
}

// UnimplementedKbInfoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKbInfoServiceServer struct {
}

func (*UnimplementedKbInfoServiceServer) UpdateKbDetailList(ctx context.Context, req *KbInfoRequest) (*KbInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKbDetailList not implemented")
}

func RegisterKbInfoServiceServer(s *grpc.Server, srv KbInfoServiceServer) {
	s.RegisterService(&_KbInfoService_serviceDesc, srv)
}

func _KbInfoService_UpdateKbDetailList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KbInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KbInfoServiceServer).UpdateKbDetailList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.KbInfoService/UpdateKbDetailList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KbInfoServiceServer).UpdateKbDetailList(ctx, req.(*KbInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KbInfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.KbInfoService",
	HandlerType: (*KbInfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateKbDetailList",
			Handler:    _KbInfoService_UpdateKbDetailList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "KbInfo.proto",
}
